<?php

namespace App\Helper;


class TypeFCM
{
    const NEW_ORDER = "NEW_ORDER"; //Đơn hàng mới
    const REFUND_ORDER = "REFUND_ORDER"; //Đơn hàng mới
    const NEW_PERIODIC_SETTLEMENT = "NEW_PERIODIC_SETTLEMENT"; //Quyết toán định kỳ
    const NEW_POST = "NEW_POST"; //Bai viet mới
    const SEND_ALL = "SEND_ALL";
    const CTV_SUCCESS = "CTV_SUCCESS"; //duyệt ctv
    const ORDER_STATUS = "ORDER_STATUS"; //Thay doi order
    const NEW_MESSAGE = "NEW_MESSAGE"; //Tin nhắn mới
    const GET_CTV = "GET_CTV"; //Yêu cầu CTV
    const CANCEL_CTV = "CANCEL_CTV"; //hủy yêu cầu CTV
    const CANCEL_CTV_PAY = "CANCEL_CTV_PAY"; //hủy yêu cầu thanh toán CTV
    const NEAR_OUT_STOCK = "NEAR_OUT_STOCK"; //Sản phẩm sắp hết hàng
    const COUNT_ORDER_END_DAY = "COUNT_ORDER_END_DAY"; //Tính số lượng đơn rồi thông báo cuối ngày
    const GOOD_NIGHT_USER = "GOOD_NIGHT_USER"; //Chúc user
    const CUSTOMER_CANCELLED_ORDER = "CUSTOMER_CANCELLED_ORDER"; //Khách đã hủy đơn hàng
    const CUSTOMER_PAID = "CUSTOMER_PAID"; //Khách đã thanh toán
    const TO_ADMIN = "TO_ADMIN"; //gửi đến admin

    const NEW_COMMENT_BUY = "NEW_COMMENT_BUY"; //Comment mua
    const NEW_COMMENT_SELL = "NEW_COMMENT_SELL"; //Comment bán

    const NEW_COMMUNITY_USER = "NEW_COMMUNITY_USER"; //Comment bán
    const NEW_COMMUNITY_BUY = "NEW_COMMUNITY_BUY"; //Bán đăng mua
    const NEW_COMMUNITY_SELL = "NEW_COMMUNITY_SELL"; //Bán đăng bán

    const NEW_CONTRACT = 'NEW_CONTRACT'; // hợp đồng mới
    const NEW_CUSTOMER_POTENTIAL = 'NEW_CUSTOMER_POTENTIAL'; // khách hàng tiềm năng mới
    const CONTRACT_HAS_CHANGED = 'CONTRACT_HAS_CHANGED';
    const NEW_HOST = 'NEW_HOST';
    const ADD_ROLE_MANAGE_TOWER = 'ADD_ROLE_MANAGE_TOWER';
    const NEW_RENTER = 'NEW_RENTER';
    const NEW_BILL = 'NEW_BILL';
    const UP_RANK_TO_HOST = 'UP_RANK_TO_HOST';
    const NEW_RESERVATION = 'NEW_RESERVATION';
    const NEW_REPORT_PROBLEM = 'NEW_REPORT_PROBLEM';
    const NEW_FIND_FAST_MOTEL = 'NEW_FIND_FAST_MOTEL';
    const NEW_REPORT_VIOLATION = 'NEW_REPORT_VIOLATION';
    const REPORT_PROBLEM_DONE = 'REPORT_PROBLEM_DONE';
    const REPORT_PROBLEM_DELETED_BY_HOST = 'REPORT_PROBLEM_DELETED_BY_HOST';
    const NEW_MO_POST = 'NEW_MO_POST';
    const NEW_MO_POST_FIND_MOTEL = 'NEW_MO_POST_FIND_MOTEL';
    const NEW_MO_POST_ROOMMATE = 'NEW_MO_POST_ROOMMATE';
    const NEW_ORDER_SERVICE = 'NEW_ORDER_SERVICE';
    const CONFIRM_CONTRACT = 'CONFIRM_CONTRACT';
    const PAYMENT_COLLABORATOR_MANAGE = 'PAYMENT_COLLABORATOR_MANAGE';
    const PAYMENT_COMMISSION_FOR_HOST = 'PAYMENT_COMMISSION_FOR_HOST';
    const CONFIRM_COMMISSION_PAYMENT_HOST_FOR_ADMIN = 'CONFIRM_COMMISSION_PAYMENT_HOST_FOR_ADMIN';
    const CONFIRMED_COMMISSION_COLLABORATOR_FOR_HOST = 'CONFIRMED_COMMISSION_COLLABORATOR_FOR_HOST';
    const CONFIRM_COMMISSION_COLLABORATOR_FOR_ADMIN = 'CONFIRM_COMMISSION_COLLABORATOR_FOR_ADMIN';
    const CONFIRM_CONTRACT_AND_DEPOSIT_PAID = 'CONFIRM_CONTRACT_AND_DEPOSIT_PAID';
    const UNCONFIRMED_CONTRACT_BY_HOST = 'UNCONFIRMED_CONTRACT_BY_HOST';
    const TERMINATION_CONTRACT = 'TERMINATION_CONTRACT';
    const BALANCE_CHANGE = 'BALANCE_CHANGE';
    const UNCONFIRMED_BILL_BY_HOST = 'UNCONFIRMED_BILL_BY_HOST';
    const POST_APPROVED = 'POST_APPROVED';
    const POST_DELETE = 'POST_DELETE';
    const POST_CANCEL = 'POST_CANCEL';
    const POST_APPROVED_AND_VERIFIED = 'POST_APPROVED_AND_VERIFIED';
    const CONTRACT_IS_ABOUT_TO_EXPIRE = 'CONTRACT_IS_ABOUT_TO_EXPIRE';
    const CONTRACT_IS_ABOUT_TO_EXPIRE_MANAGE = 'CONTRACT_IS_ABOUT_TO_EXPIRE_MANAGE';
    const CONTRACT_EXPIRED = 'CONTRACT_EXPIRED';
    const CONTRACT_EXPIRED_MANAGE = 'CONTRACT_EXPIRED_MANAGE';
    const BILL_HAS_PAID = 'BILL_HAS_PAID';
    const BILL_HAS_PAID_WAIT_HOST_CONFIRM = 'BILL_HAS_PAID_WAIT_HOST_CONFIRM';
    const BILL_CANCEL_BY_RENTER = 'BILL_CANCEL_BY_RENTER';
    const BILL_CHANGED = 'BILL_CHANGED';
    const RENTER_CONFIRMED = 'RENTER_CONFIRMED';
    const BILL_NEED_PAID = 'BILL_NEED_PAID';
    const ORDER_SUCCESS = 'ORDER_SUCCESS';
    const ORDER_SHIPPING = 'ORDER_SHIPPING';
    const CANCEL_ORDER = 'CANCEL_ORDER';
    const PAYMENT_DATE_MOTEL_IS_COMING = 'PAYMENT_DATE_MOTEL_IS_COMING';
    const MATURITY_MOTEL = 'MATURITY_MOTEL';
    const NEW_REQUEST_WITHDRAWAL = 'NEW_REQUEST_WITHDRAWAL';
    const APPROVED_REQUEST_WITHDRAWAL = 'APPROVED_REQUEST_WITHDRAWAL';
    const UNAPPROVED_REQUEST_WITHDRAWAL = 'UNAPPROVED_REQUEST_WITHDRAWAL';
}
